export const skillOptions = [
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "Java",
  "HTML",
  "CSS",
  "SQL",
  "Angular",
  "Vue.js",
  "Ruby",
  "C#",
  "C++",
  "PHP",
  "Swift",
  "Kotlin",
  "TypeScript",
  "Bootstrap",
  "jQuery",
  "MongoDB",
  "Redux",
  "Express.js",
  "Django",
  "Flask",
  "Spring Framework",
  "Hibernate",
  "ASP.NET",
  ".NET Core",
  "PHP Laravel",
  "Symfony",
  "ASP.NET MVC",
  "Ruby on Rails",
  "Go (Golang)",
  "Rust",
  "Dart",
  "Flutter",
  "Android Development",
  "iOS Development",
  "Xamarin",
  "GraphQL",
  "AWS (Amazon Web Services)",
  "TensorFlow",
  "PyTorch",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Artificial Intelligence (AI)",
  "Data Science",
  "Big Data",
  "Hadoop",
  "Spark",
  "Kafka",
  "Elasticsearch",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Git",
  "CI/CD",
  "RESTful APIs",
  "Microservices",
  "OAuth",
  "JSON Web Tokens (JWT)",
  "WebSockets",
  "Firebase",
];
